### ISSUE TITLE
Add memory cache

### ISSUE THREAD

**Issue by lanlou1554** [cmu-db/15721-s24-cache1#14]
Add in-memory cache for small and hot data. The data in memory are not backed up by disk cache, which means the data in memory cache and the data in disk cache don't overlap.
The quick roadmap should be: get data -> check memory cache -> check disk cache -> pull data from S3.
After pulling data from S3, if the file size is small, we store it into memory cache, otherwise it should be stored into disk cache.

   For in-memory cache, currently we can have 2 designs of the whole procedure for write data into cache:
   Generally, memory cache will record a hashmap (key -> vector of Bytes) to record the data. (Note: in current version, the file represents all the files for one S3 request, and we should optimize it later.)
   1. First Design:
      1. Get the file size and file from S3.
      2. Storage_manager will check the file size, if it is small, try to put it into memory cache, (remember also write the evicted memory key to disk if applicable); otherwise, try to write it into disk cache.
   
      (Disk cache and memory cache could consume a `S3Reader` as an input parameter for write_data in this case)
   2. Second Dsign:
      1. Get the file from S3 (as S3Reader).
      2. Storage_manager will convert S3Reader to stream, and call next to get `Bytes`. Then, it will first try to write it to memory cache. 
   
            Memory cache will first add the key into its hashmap, and record the `Bytes`. But when it finds the size is too large, it will return false and also return the vector of `Bytes` for this key.

            Storage_manager will write the file with `false` return value from memory cache `or` the evicted file to disk.

      (Disk cache and memory cache should accept `Bytes` as an input parameter for write_data in this case)
   
   For me, the first design is very clear and less prone to bugs, and the second design can save the cost of requesting S3 to get the size.

**Comment by lanlou1554** [comment]
Due to API constraints of DataStoreCache, I currently adopt method 2.
As expected, the code becomes very ugly : ( Let me think about how to refine it...

**Comment by lanlou1554** [comment]
Another thing worth considering (maybe future optimization?):
When some small data gets evicted from mem_cache, then it becomes hot (frequent access). But in the current implementation, there is no chance for this data to go back to the memory cache.
(Maybe we when get_data_from_cache, we can **identify** this kind of data, delete it from disk cache, and re-add it into memory cache. But how to identify it?)

**Comment by xx01cyx** [comment]
> When some small data gets evicted from mem_cache, then it becomes hot (frequent access)

~Why's that? The fact that it's evicted denotes that it's not so frequently used?~

yeah we should have some strategy to move the data back to the memory
